In [1]:
import numpy as np

# ============================================
# Exam Marks Statistics Project
# ============================================

# 1. Load exam marks data
marks = np.array([78, 85, 33, 66, 15, 88, 90, 59, 29, 70])

print("Exam Marks:")
print(marks)


# 2. Compute basic statistics

average = np.mean(marks)
median = np.median(marks)
std_deviation = np.std(marks)

print("\n--- Class Statistics ---")
print("Average Marks:", average)
print("Median Marks:", median)
print("Standard Deviation:", round(std_deviation, 2))


# 3. Analyze performance

above_average = marks[marks > average]
failed_students = marks[marks < 35]

print("\n--- Performance Insights ---")

print("Students scoring above average:")
print(above_average)

print("Number of students above average:", len(above_average))

print("\nStudents who failed (marks < 35):")
print(failed_students)

print("Number of failed students:", len(failed_students))


# 4. Find highest and lowest scores

highest_score = np.max(marks)
lowest_score = np.min(marks)

print("\n--- Extremes ---")
print("Highest Score:", highest_score)
print("Lowest Score:", lowest_score)

Exam Marks:
[78 85 33 66 15 88 90 59 29 70]

--- Class Statistics ---
Average Marks: 61.3
Median Marks: 68.0
Standard Deviation: 25.43

--- Performance Insights ---
Students scoring above average:
[78 85 66 88 90 70]
Number of students above average: 6

Students who failed (marks < 35):
[33 15 29]
Number of failed students: 3

--- Extremes ---
Highest Score: 90
Lowest Score: 15
